Specific_Url_navigation/urls.py
from django.contrib import admin
from django.urls import path,include
import app1
import app2
import app3

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
    path('app3/',include('app3.urls')),
]

app1/urls.py
from app1.views import *
from django.urls import path
app_name='hi'
urlpatterns=[
    path('First_World_War/',First_World_War,name='First_World_War'),
]

app2/urls.py
from app2.views import *
from django.urls import path
app_name='hello'
urlpatterns=[
    path('Second_World_War/',Second_World_War,name='Second_World_War')
]

app3/urls.py
from app3.views import *
from django.urls import path
app_name='hello django'
urlpatterns=[
    path('Kings/',Kings,name='Kings')
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app3/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.

def First_World_War(request):
    return render(request,'First_World_War.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def Second_World_War(request):
    return render(request,'Second_World_War.html')

app3/views.py
from django.shortcuts import render

# Create your views here.
def Kings(request):
    return render(request,'Kings.html')

templates/First_World_War.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<style>
    *
    {
        margin: 0px;
    }
    #header
    {
        background:linear-gradient(45deg,yellow,deeppink,green);
        color:white;
        align-items: center;
        height: 40px;
        width: auto;
    }
    #header:hover
    {
        text-decoration: underline;
        
    }
    #main_section
    {
        color:white;
        background-color:blue;
    }
    #footer
    {
        color:white;
       
    
        background-color:yellow;
        
    }
    #footer>button
    {
        background-color:lime;
        width:auto;
        height:auto;
        padding:8px;
       

    }
    #footer>button>a
    {
      color:white;
      text-decoration: none;

    }
    #footer>button>a:hover
    {
        text-decoration:underline;
        border: 0px 20px auto solid;
        box-shadow:  opx auto 10px blue;
    }

</style>
<body>
    <div id="header">
    <center><h1>About First World War</h1></center>
    </div>
    <div id="main_section">
    <p >World War I, also known as the First World War or the Great War in historical contexts,
        was a global conflict from 1914 to 1918. It was fought between two coalitions:
        the Allied Powers and the Central Powers. Fighting took place throughout Europe, the Middle East, Africa, the Pacific, and parts of Asia.
        World War I (WWI or WW1), also known as the First World War or the Great War in historical contexts, was a global conflict from 1914 to 1918. It was fought between two coalitions: the Allied Powers and the Central Powers. Fighting took place throughout Europe, the Middle East, Africa, the Pacific, and parts of Asia. One of the deadliest wars in history, it resulted in an estimated 9 million soldiers dead and 23 million wounded, plus another 5 million civilian deaths from various causes. Millions more died as a result of genocide, and the war was a major factor in the 1918 Spanish flu pandemic.

        The first decade of the 20th century saw increasing diplomatic tension between
        the European great powers. This reached a breaking point on 28 June 1914, when a Bosnian Serb named
        Gavrilo Princip assassinated Archduke Franz Ferdinand, heir to the Austro-Hungarian throne. 
        Austria-Hungary held Serbia responsible, and declared war on 28 July. Russia came to Serbia's defence, and by 4 August,
        ermany, France, and Britain were drawn into the war, with the Ottoman Empire joining in November of that same year.
        The first decade of the 20th century saw increasing diplomatic tension between the European great powers. This reached 
        a breaking point on 28 June 1914, when a Bosnian Serb named Gavrilo Princip assassinated Archduke Franz Ferdinand, heir to the
        Austro-Hungarian throne. Austria-Hungary held Serbia responsible, and declared war on 28 July. Russia came to Serbia's defence, 
        and by 4 August, Germany, France, and Britain were drawn into the war, with the Ottoman Empire joining in November of that same year.

        Germany's strategy in 1914 was to first defeat France, then transfer forces to the Russian front.
    However, this failed, and by the end of 1914, the Western Front consisted of a continuous
    line of trenches stretching from the English Channel to Switzerland. The Eastern Front was more dynamic, 
    but neither side could gain a decisive advantage, despite costly offensives. As the war expanded to more fronts,
    Bulgaria, Romania, Greece, Italy and others joined in from 1915 onward.
    In early 1917, the United States entered the war on the side of the Allies, and later the same year, the
    Bolsheviks seized power in the Russian October Revolution, making peace with the Central Powers in early 1918.
    Germany launched an offensive in the west in March 1918, and despite initial success,
    it left the German Army exhausted and demoralised. A successful Allied counter-offensive later that year caused a collapse of 
    the German frontline. By the end of 1918, Bulgaria, the Ottoman Empire and Austria-Hungary agreed to armistices with the Allies,
    leaving Germany isolated. Facing revolution at home and with his army on the verge of mutiny,
    Kaiser Wilhelm II abdicated on 9 November.
    World War II in September 1939.</p>
    
    <center>
        <div>
          <img src="https://www.clearias.com/up/First-World-War.png"width="310px" height="310px"> 
          <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRGVAyYH-tLnSkIek4fBKgrVib9woJiCA9tA&usqp=CAU" width="310px" height="310px">
          <br>
        </div>
        <div id="footer">
          <button><a href="{% url 'hello:Second_World_War'%}">Second war</a></button>
          <button><a href="{% url 'hello django:Kings'%}">Kings</a></button>
          <h2>Copy Rights:&copy;2023</h2>
         <small>All rirhts are reserved &reg</small>
         <p>Developed and Maintained by <a href="#" style="color:blue">Blessie</a></p>
       </div>
       </center>       
    
</body>
</html>

templates/Kings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<style>
    *
    {
        margin: 0px;
    }
    #header
    {
        background:linear-gradient(45deg,blue,white,green);
        color:aqua;
        align-content: center;
        height: 40px;
        width: auto;
    }
    #header:hover
    {
        text-decoration: underline;
    }
    #main_section
    {
        color:white;
        background-color:palevioletred
    }
    #link
    {
        color:white;
        align-;
    
        background-color:aqua;
        
    }
    #link>button
    {
        background-color:lime;
        text-decoration:none;
        color:lime;
        padding: 10px;
    }
    #link>button>a
    {
      color:white;
      text-decoration: none;

    }
    #link>button>a:hover
    {
        text-decoration:underline;
        box-shadow:  opx auto 10px blue;
    }

</style>

<body>
    <div id="header">
   <center> <h1>About Kings in Two World Wars</h1></center>
    </div>
    <div id="main_section">
    <p> In the years before the First World War, the great European powers were ruled by three first cousins: King George
        V of Britain, Kaiser Wilhelm II of Germany, and Tsar Nicholas II of Russia. Together
        they presided over the last years of dynastic Europe and the outbreak of the most destructive war the world had
        ever seen, a war that set twentieth-century Europe on course to be the most violent continent in the history of the world.

        Through brilliant and often darkly comic portraits of these men and their lives, 
        their foibles and obsessions, Miranda Carter delivers the tragicomic story of Europe’s early 
        twentieth-century aristocracy, a solipsistic world preposterously out of kilter with its times.In the years before the First World War,
        the great European powers were ruled by three first cousins: King George V of Britain, Kaiser Wilhelm II of Germany,
        and Tsar Nicholas II of Russia. Together, they presided over the last years of dynastic Europe and the outbreak of the most
        destructive war the world had ever seen, a war that set twentieth-century Europe on course to be the most violent continent 
        in the history of the world.
        
        Through brilliant and often darkly comic portraits of these men and their lives,
        their foibles and obsessions, Miranda Carter delivers the tragicomic story of
        Europe’s early twentieth-century aristocracy,
        a solipsistic world preposterously out of kilter with its times.In the years before the First World War, the great
        European powers were ruled by three first cousins: King George V of Britain,
        Kaiser Wilhelm II of Germany, and Tsar
        Nicholas II of Russia. Together, they presided over the last years of dynastic Europe and the outbreak of the most
        destructive war the world had ever seen, a war that set twentieth-century Europe on course to be the most violent continent 
        in the history of the world.
        
        Through brilliant and often darkly comic portraits of these men and their lives, 
        
        their foibles and obsessions, Miranda Carter delivers the tragicomic story
        of Europe’s early twentieth-century aristocracy, 
        a solipsistic world preposterously out of kilter with its times. </p>        
        <center>
            <div>
                <img src="https://www.clearias.com/up/First-World-War.png"width="300px" height="300px"> 
                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRGVAyYH-tLnSkIek4fBKgrVib9woJiCA9tA&usqp=CAU" width="300px" height="300px">
            <br>
            </div>
        </div>
        </center>
        <center>
            <div id="link">            
                <button><a href="{% url 'hello:Second_World_War'%}">Back TO Second War</a></button>
                <button><a href="{% url 'hi:First_World_War'%}">Back TO First War</a></button>
                <h1>Copy Rights:&copy;2023</h1>
                <h2>All rirhts are reserved &reg</h2>
                <p>Developed and Maintained by <a href="#" style="color: deeppink;">Blessie</a></p>
            </div>
        </center>
    
    </body>
</html>

templates/Second_World_War.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<style>
    *
    {
        margin: 0px;
    }
    #header
    {
        background-color: rgb(255, 98, 0);
        color:white;
        align-content: center;
        height:40px;
        width: auto;
        
    }
    #header:hover
    {
        text-decoration: underline;
    }
    #main_section
    {
        color:white;
        background-color: cyan;
    }
    #footer
    {
        color:white;
       
    
        background-color:yellow;
        
    }
    #footer>button
    {
        background-color:lime;
        text-decoration:none;
        color:lime;
        padding: 5px;
    }
    #footer>button>a
    {
      color:white;
      text-decoration: none;

    }
    #footer>button>a:hover
    {
        text-decoration:underline;
        box-shadow:opx auto 10px blue;
    }

</style>

<body>
    <div id="header">
        <center><h1>About Second World War</h1></center>
    </div>
    <div id="main_section">
        <p>World War 2, also known as the Second World War or the Great War in historical contexts,
        was a global conflict from 1914 to 1918. It was fought between two coalitions:
        the Allied Powers and the Central Powers. Fighting took place throughout Europe, the Middle East, Africa, the Pacific, and parts of Asia.
        World War I (WWI or WW1), also known as the First World War or the Great War in historical contexts, was a global conflict from 1914 to 1918. It was fought between two coalitions: the Allied Powers and the Central Powers. Fighting took place throughout Europe, the Middle East, Africa, the Pacific, and parts of Asia. One of the deadliest wars in history, it resulted in an estimated 9 million soldiers dead and 23 million wounded, plus another 5 million civilian deaths from various causes. Millions more died as a result of genocide, and the war was a major factor in the 1918 Spanish flu pandemic.

        The first decade of the 20th century saw increasing diplomatic tension between
        the European great powers. This reached a breaking point on 28 June 1914, when a Bosnian Serb named
        Gavrilo Princip assassinated Archduke Franz Ferdinand, heir to the Austro-Hungarian throne. 
        Austria-Hungary held Serbia responsible, and declared war on 28 July. Russia came to Serbia's defence, and by 4 August,
        Germany, France, and Britain were drawn into the war, with the Ottoman Empire joining in November of that same year.
        The first decade of the 20th century saw increasing diplomatic tension between the European great powers.
        This reached a breaking point on 28 June 1914, when a Bosnian Serb named Gavrilo Princip assassinated Archduke Franz Ferdinand,
        heir to the Austro-Hungarian throne. Austria-Hungary held Serbia responsible, and declared war on 28 July. 
        Russia came to Serbia's defence, and by 4 August, Germany, France, and Britain were drawn into the war,
        with the Ottoman Empire joining in November of that same year.

        Germany's strategy in 1914 was to first defeat France, then transfer forces to the Russian front.
        However, this failed, and by the end of 1914, the Western Front consisted of a continuous
        line of trenches stretching from the English Channel to Switzerland. The Eastern Front was more dynamic, 
        but neither side could gain a decisive advantage, despite costly offensives. As the war expanded to more fronts,
         Bulgaria, Romania, Greece, Italy and others joined in from 1915 onward.
        In early 1917, the United States entered the war on the side of the Allies, and later the same year, the
        Bolsheviks seized power in the Russian October Revolution, making peace with the Central Powers in early 1918.
        Germany launched an offensive in the west in March 1918, and despite initial success,
       it left the German Army exhausted and demoralised. A successful Allied counter-offensive later that year caused a collapse of 
        the German frontline. By the end of 1918, Bulgaria, the Ottoman Empire and Austria-Hungary agreed to armistices with the Allies,
       Germany isolated. Facing revolution at home and with his army on the verge of mutiny, Kaiser Wilhelm II abdicated on 9 November.
       </p>
       
       <center>
        <div>
           <img src="https://www.clearias.com/up/First-World-War.png"width="310px" height="310px">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRGVAyYH-tLnSkIek4fBKgrVib9woJiCA9tA&usqp=CAU"width="310px" height="310px">
               <br>
       </div>
    </div>
      </center>
      <center>
        
       <div id="footer">
            <button><a href="{% url 'hi:First_World_War'%}">First War</a></button>
            <button><a href="{% url 'hello django:Kings'%}">Kings</a></button>
            <h1>Copy Rights:&copy;2023</h1>
            <h2>All rirhts are reserved &reg</h2>
            <p>Developed and Maintained by <a href="#" style="color:aqua">Blessie</a></p>
         </div>
         </center>

</body>
</html>